spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000

crypto:
  password-pepper: ${PASSWORD_PEPPER:default_peper_from_config}

test-config-params:
  string-param: this is test string from git config repository
  integer-param: 10000;
  boolean-param: false;
